version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 61972:1972
      - 61773:52773
      - 61888:8888
    volumes:
      - ./:/irisdev/app